version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "3001:3001"
    networks:
      - app-network

  frontend:
    build: ./src
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
