version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong@Password123"
      ACCEPT_EULA: "Y"
    ports:
      - "11433:1433"
    networks:
      - app-network
    volumes:
      - ./init.sql:/usr/src/app/init.sql
    user: root
    command: >
      bash -c "
        /opt/mssql/bin/sqlservr & 
        sleep 20 && 
        apt-get update && apt-get install -y mssql-tools unixodbc-dev &&
        echo 'export PATH=$PATH:/opt/mssql-tools/bin' >> ~/.bashrc && 
        /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'YourStrong@Password123' -i /usr/src/app/init.sql &&
        wait
      "
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong@Password123", "-Q", "SELECT 1" ]
      interval: 10s
      retries: 5
      start_period: 20s

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: backend
    ports:
      - "3001:3001"
    networks:
      - app-network
    depends_on:
      sqlserver:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: frontend
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:3001

networks:
  app-network:
    driver: bridge
